changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - "feat"
    - title: "🛠 Maintenance"
      labels:
        - "chore"
    - title: "🐛 Bug Fixes"
      labels:
        - "fix"
