package audit

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// Reversibility classifies whether a past mutation can be undone.
type Reversibility string

const (
	// ReversibilityYes means a full inverse operation is available.
	ReversibilityYes Reversibility = "yes"
	// ReversibilityPartial means the system will self-recover (e.g. a pod
	// managed by a controller) but no explicit inverse op is generated.
	ReversibilityPartial Reversibility = "partial"
	// ReversibilityNo means the operation cannot be undone (connection already
	// gone, restart already happened, etc.).
	ReversibilityNo Reversibility = "no"
)

// RollbackPlan is the derived inverse operation for a single tool_execution event.
// Generated by DeriveRollbackPlan from the event's Tool and Tool.PreState fields.
type RollbackPlan struct {
	// OriginalEventID is the tool_execution event this plan reverses.
	OriginalEventID string `json:"original_event_id"`
	// OriginalTool is the tool that was executed (e.g. "scale_deployment").
	OriginalTool string `json:"original_tool"`
	// OriginalTraceID links back to the originating user request.
	OriginalTraceID string `json:"original_trace_id"`
	// Reversibility classifies whether this plan can be executed.
	Reversibility Reversibility `json:"reversibility"`
	// NotReversibleReason explains why the operation cannot be undone.
	NotReversibleReason string `json:"not_reversible_reason,omitempty"`
	// InverseOp is the compensating operation to execute. Nil when Reversibility != "yes".
	InverseOp *InverseOperation `json:"inverse_op,omitempty"`
	// GeneratedAt is when this plan was derived.
	GeneratedAt time.Time `json:"generated_at"`
}

// InverseOperation describes the compensating call to dispatch.
type InverseOperation struct {
	// Agent is the A2A agent to call (e.g. "k8s", "database").
	Agent string `json:"agent"`
	// Tool is the tool name to invoke (e.g. "scale_deployment").
	Tool string `json:"tool"`
	// Args are the arguments for the compensating call.
	Args map[string]any `json:"args"`
	// Description is a human-readable summary of what the rollback will do.
	Description string `json:"description"`
}

// ScalePreState captures the replica count before a scale_deployment call.
type ScalePreState struct {
	Namespace        string `json:"namespace"`
	DeploymentName   string `json:"deployment"`
	PreviousReplicas int    `json:"previous_replicas"`
}

// DMLPreState captures the affected rows before a DML operation (INSERT/UPDATE/DELETE).
// Tier 1 (row-capture): rows are fetched via SELECT with the same WHERE condition.
// Tier 2 (WAL decode): rows are extracted from the WAL change stream; see WALCapture.
type DMLPreState struct {
	Schema    string `json:"schema"`
	Table     string `json:"table"`
	Operation string `json:"operation"` // "insert", "update", "delete"
	// PKColumns lists the primary key column names used to identify rows.
	PKColumns []string `json:"pk_columns"`
	// Rows holds the old row values for UPDATE and DELETE operations (Tier 1 or 2).
	Rows []map[string]any `json:"rows,omitempty"`
	// InsertedPKs holds the primary key values returned by INSERT ... RETURNING (Tier 1).
	InsertedPKs []map[string]any `json:"inserted_pks,omitempty"`
	// RowCount is the number of rows captured.
	RowCount int `json:"row_count"`
	// CapturedAt is when the snapshot was taken.
	CapturedAt time.Time `json:"captured_at"`
	// Tier is 1 (row-capture) or 2 (WAL decode).
	Tier int `json:"tier"`
	// WAL holds the raw WAL capture for Tier 2. Nil for Tier 1.
	WAL *WALCapture `json:"wal,omitempty"`
}

// WALCapture holds the logical decoding output bracketing a single DML operation.
type WALCapture struct {
	SlotName   string      `json:"slot_name"`
	LSNBefore  string      `json:"lsn_before"`
	LSNAfter   string      `json:"lsn_after"`
	Changes    []WALChange `json:"changes"`
	CapturedAt time.Time   `json:"captured_at"`
}

// WALChange represents one decoded row change from wal2json.
type WALChange struct {
	// Kind is "insert", "update", or "delete".
	Kind string `json:"kind"`
	// Schema and Table identify the affected relation.
	Schema string `json:"schema"`
	Table  string `json:"table"`
	// NewValues holds column values after the change (INSERT and UPDATE).
	NewValues map[string]any `json:"new_values,omitempty"`
	// OldValues holds column values before the change. Populated for UPDATE/DELETE
	// only when the table has REPLICA IDENTITY FULL; otherwise only PKValues is set.
	OldValues map[string]any `json:"old_values,omitempty"`
	// PKValues holds the primary key column values used to identify the row.
	PKValues map[string]any `json:"pk_values"`
}

// DeriveRollbackPlan reads a tool_execution audit event and produces a RollbackPlan.
// For irreversible operations the plan has Reversibility="no" and no InverseOp.
// Returns an error only if the event structure is malformed (nil Tool).
func DeriveRollbackPlan(event *Event) (*RollbackPlan, error) {
	if event.Tool == nil {
		return nil, fmt.Errorf("event %s has no tool execution", event.EventID)
	}
	plan := &RollbackPlan{
		OriginalEventID: event.EventID,
		OriginalTool:    event.Tool.Name,
		OriginalTraceID: event.TraceID,
		GeneratedAt:     time.Now().UTC(),
	}

	switch event.Tool.Name {
	case "scale_deployment":
		return deriveScaleRollback(plan, event)
	case "delete_pod":
		plan.Reversibility = ReversibilityPartial
		plan.NotReversibleReason = "Pod deletion is partially reversible: the pod's owning " +
			"controller (ReplicaSet, StatefulSet, DaemonSet) will recreate the pod automatically. " +
			"If no controller manages this pod, it is permanently gone. " +
			"No explicit inverse operation is generated."
		return plan, nil
	case "restart_deployment":
		plan.Reversibility = ReversibilityNo
		plan.NotReversibleReason = "A rollout restart cannot be undone: the restart has already " +
			"happened. To roll back to a previous image, use a deployment rollback " +
			"(kubectl rollout undo). Image rollbacks are not currently supported by this system."
		return plan, nil
	case "terminate_connection", "terminate_idle_connections", "cancel_query":
		plan.Reversibility = ReversibilityNo
		plan.NotReversibleReason = fmt.Sprintf(
			"%s: the connection or query is already gone and cannot be restored. "+
				"The get_session_info pre-flight already surfaced the rollback cost estimate "+
				"before this operation was approved.", event.Tool.Name)
		return plan, nil
	case "exec_update", "exec_delete", "exec_insert":
		return deriveDMLRollback(plan, event)
	default:
		plan.Reversibility = ReversibilityNo
		plan.NotReversibleReason = fmt.Sprintf(
			"tool %q has no registered inverse operation", event.Tool.Name)
		return plan, nil
	}
}

// deriveScaleRollback builds a RollbackPlan for scale_deployment events.
func deriveScaleRollback(plan *RollbackPlan, event *Event) (*RollbackPlan, error) {
	if len(event.Tool.PreState) == 0 {
		plan.Reversibility = ReversibilityNo
		plan.NotReversibleReason = "Pre-mutation state was not captured for this scale_deployment " +
			"event. Events recorded before rollback support was added cannot be reversed automatically."
		return plan, nil
	}
	var pre ScalePreState
	if err := json.Unmarshal(event.Tool.PreState, &pre); err != nil {
		return nil, fmt.Errorf("unmarshal ScalePreState for event %s: %w", event.EventID, err)
	}
	if pre.PreviousReplicas == 0 {
		plan.Reversibility = ReversibilityNo
		plan.NotReversibleReason = "Pre-mutation replica count was 0 or could not be parsed; " +
			"cannot safely restore to that state."
		return plan, nil
	}
	plan.Reversibility = ReversibilityYes
	plan.InverseOp = &InverseOperation{
		Agent: "k8s",
		Tool:  "scale_deployment",
		Args: map[string]any{
			"namespace":  pre.Namespace,
			"deployment": pre.DeploymentName,
			"replicas":   pre.PreviousReplicas,
		},
		Description: fmt.Sprintf("restore deployment/%s in namespace %s to %d replica(s)",
			pre.DeploymentName, pre.Namespace, pre.PreviousReplicas),
	}
	return plan, nil
}

// deriveDMLRollback builds a RollbackPlan for DML tool events (exec_update, exec_delete, exec_insert).
func deriveDMLRollback(plan *RollbackPlan, event *Event) (*RollbackPlan, error) {
	if len(event.Tool.PreState) == 0 {
		plan.Reversibility = ReversibilityNo
		plan.NotReversibleReason = "Pre-mutation state was not captured for this DML event. " +
			"Events recorded before rollback support was added cannot be reversed automatically."
		return plan, nil
	}
	var pre DMLPreState
	if err := json.Unmarshal(event.Tool.PreState, &pre); err != nil {
		return nil, fmt.Errorf("unmarshal DMLPreState for event %s: %w", event.EventID, err)
	}
	if pre.RowCount == 0 {
		plan.Reversibility = ReversibilityYes
		plan.InverseOp = &InverseOperation{
			Agent:       "database",
			Tool:        "exec_sql",
			Args:        map[string]any{"sql": "-- no rows affected; no inverse SQL needed"},
			Description: "no rows were affected by the original operation; nothing to reverse",
		}
		return plan, nil
	}

	var sql string
	var desc string
	var err error

	switch pre.Operation {
	case "insert":
		sql, desc, err = inverseInsertSQL(&pre)
	case "update":
		sql, desc, err = inverseUpdateSQL(&pre)
	case "delete":
		sql, desc, err = inverseDeleteSQL(&pre)
	default:
		plan.Reversibility = ReversibilityNo
		plan.NotReversibleReason = fmt.Sprintf("unknown DML operation %q", pre.Operation)
		return plan, nil
	}
	if err != nil {
		return nil, fmt.Errorf("derive inverse SQL for %s event %s: %w", pre.Operation, event.EventID, err)
	}

	tierNote := "Tier 1 (row-capture)"
	if pre.Tier == 2 {
		tierNote = "Tier 2 (WAL decode)"
	}
	plan.Reversibility = ReversibilityYes
	plan.InverseOp = &InverseOperation{
		Agent: "database",
		Tool:  "exec_sql",
		Args: map[string]any{
			"sql":  sql,
			"tier": pre.Tier,
		},
		Description: fmt.Sprintf("%s — captured via %s (%d row(s))", desc, tierNote, pre.RowCount),
	}
	return plan, nil
}

// inverseInsertSQL generates DELETE SQL that removes the rows inserted by the original INSERT.
// Uses the InsertedPKs captured via RETURNING.
func inverseInsertSQL(pre *DMLPreState) (sql, desc string, err error) {
	if len(pre.InsertedPKs) == 0 || len(pre.PKColumns) == 0 {
		return "", "", fmt.Errorf("INSERT pre-state missing InsertedPKs or PKColumns")
	}
	qualTable := qualifiedTable(pre.Schema, pre.Table)

	if len(pre.PKColumns) == 1 {
		col := pre.PKColumns[0]
		vals := make([]string, 0, len(pre.InsertedPKs))
		for _, row := range pre.InsertedPKs {
			vals = append(vals, fmt.Sprintf("%v", row[col]))
		}
		sql = fmt.Sprintf("DELETE FROM %s WHERE %s IN (%s)",
			qualTable, col, strings.Join(vals, ", "))
	} else {
		// Composite PK: one condition per row
		conds := make([]string, 0, len(pre.InsertedPKs))
		for _, row := range pre.InsertedPKs {
			parts := make([]string, 0, len(pre.PKColumns))
			for _, col := range pre.PKColumns {
				parts = append(parts, fmt.Sprintf("%s = %v", col, row[col]))
			}
			conds = append(conds, "("+strings.Join(parts, " AND ")+")")
		}
		sql = fmt.Sprintf("DELETE FROM %s WHERE %s", qualTable, strings.Join(conds, " OR "))
	}
	desc = fmt.Sprintf("delete %d inserted row(s) from %s", len(pre.InsertedPKs), qualTable)
	return sql, desc, nil
}

// inverseUpdateSQL generates UPDATE SQL that restores each row to its pre-mutation values.
func inverseUpdateSQL(pre *DMLPreState) (sql, desc string, err error) {
	if len(pre.Rows) == 0 || len(pre.PKColumns) == 0 {
		return "", "", fmt.Errorf("UPDATE pre-state missing Rows or PKColumns")
	}
	qualTable := qualifiedTable(pre.Schema, pre.Table)

	stmts := make([]string, 0, len(pre.Rows))
	for _, row := range pre.Rows {
		// SET clause: all columns except PKs
		setClauses := make([]string, 0, len(row))
		whereClauses := make([]string, 0, len(pre.PKColumns))
		pkSet := make(map[string]bool, len(pre.PKColumns))
		for _, pk := range pre.PKColumns {
			pkSet[pk] = true
			whereClauses = append(whereClauses, fmt.Sprintf("%s = %v", pk, row[pk]))
		}
		for col, val := range row {
			if pkSet[col] {
				continue
			}
			if val == nil {
				setClauses = append(setClauses, fmt.Sprintf("%s = NULL", col))
			} else {
				setClauses = append(setClauses, fmt.Sprintf("%s = %v", col, val))
			}
		}
		if len(setClauses) == 0 {
			continue // only PKs — nothing to restore
		}
		stmts = append(stmts,
			fmt.Sprintf("UPDATE %s SET %s WHERE %s",
				qualTable,
				strings.Join(setClauses, ", "),
				strings.Join(whereClauses, " AND ")))
	}
	sql = strings.Join(stmts, ";\n")
	desc = fmt.Sprintf("restore %d updated row(s) in %s to pre-mutation values", len(pre.Rows), qualTable)
	return sql, desc, nil
}

// inverseDeleteSQL generates INSERT SQL that re-inserts the rows deleted by the original DELETE.
func inverseDeleteSQL(pre *DMLPreState) (sql, desc string, err error) {
	if len(pre.Rows) == 0 {
		return "", "", fmt.Errorf("DELETE pre-state missing Rows")
	}
	qualTable := qualifiedTable(pre.Schema, pre.Table)

	// Collect ordered column names from the first row
	first := pre.Rows[0]
	cols := make([]string, 0, len(first))
	for col := range first {
		cols = append(cols, col)
	}

	valRows := make([]string, 0, len(pre.Rows))
	for _, row := range pre.Rows {
		vals := make([]string, 0, len(cols))
		for _, col := range cols {
			v := row[col]
			if v == nil {
				vals = append(vals, "NULL")
			} else {
				vals = append(vals, fmt.Sprintf("'%v'", v))
			}
		}
		valRows = append(valRows, "("+strings.Join(vals, ", ")+")")
	}
	sql = fmt.Sprintf("INSERT INTO %s (%s) VALUES\n  %s",
		qualTable,
		strings.Join(cols, ", "),
		strings.Join(valRows, ",\n  "))
	desc = fmt.Sprintf("re-insert %d deleted row(s) into %s", len(pre.Rows), qualTable)
	return sql, desc, nil
}

func qualifiedTable(schema, table string) string {
	if schema == "" || schema == "public" {
		return table
	}
	return schema + "." + table
}
